plugins {
    id 'java'
}

group = 'com.fast.fastcollection'
version = '1.2'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'it.unimi.dsi:fastutil:8.5.16'

     testImplementation 'org.openjdk.jmh:jmh-core:1.37'
     testAnnotationProcessor 'org.openjdk.jmh:jmh-generator-annprocess:1.37'

     testImplementation 'org.assertj:assertj-core:3.27.7'
     testImplementation 'org.mockito:mockito-core:5.10.0'
}

test {
    useJUnitPlatform()
}

afterEvaluate {
    tasks.withType(org.gradle.jvm.tasks.Jar).configureEach {
        destinationDirectory = file('build/libs/')
        manifest.attributes([
                'FMLModType': 'GAMELIBRARY'
        ])
    }
}